# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
      - name: Prepare Hugo
        run: git submodule sync && git submodule update --init
      - name: Build
        run: hugo --gc --minify --cleanDestinationDir
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '276.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -d -c -r public gs://blog.cereto.com
      # - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://blog.cereto.com/**/*.html
      # - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://blog.cereto.com/js/*.js
      # - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://blog.cereto.com/css/*.css