# .github/workflows/my-workflow.yml
name: firebase-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
      - name: Prepare Hugo
        run: git submodule sync && git submodule update --init
      - name: Build
        run: hugo --gc --minify --cleanDestinationDir
      # Fetch Hugo to Firebase docker image
      - uses: wajahatkarim3/Hugo-On-Fire@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}